array_width = 0
attr_fn_like_width = 80
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
chain_width = 144
combine_control_expr = false
comment_width = 160
condense_wildcard_suffixes = true
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_params_layout = "Tall"
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_bodies = true
hard_tabs = false
hex_literal_case = "Upper"
imports_granularity = "Crate"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
match_block_trailing_comma = true
max_width = 160
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
style_edition = "2024"
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
