name: Default
description: When one of the predefined templates doesn't match
assignees:
- stop5
labels:
  - bug
title: "[Bug] <title>"
body:
- type: input
  id: kernel-version
  attributes:
    label: Kernel Version
    placeholder: "6.0.0"
  validations:
    required: true

- type: input
  id: library-version
  attributes:
    label: Library Version
    placeholder: "0.4.0"
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    value: |
      let instance = NtSync::new().unwrap();
      let object = instance.new_();
    placeholder: |
      let instance = NtSync::new().unwrap();
      let object = instance.new_();
    render: rust
  validations:
    required: false

- type: textarea
  attributes:
    label: Other things to mention
    render: markdown
  validations:
    required: false
